<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DTOs\**" />
    <Compile Remove="Interfaces\**" />
    <Compile Remove="OrdemServicos\Models\**" />
    <EmbeddedResource Remove="DTOs\**" />
    <EmbeddedResource Remove="Interfaces\**" />
    <EmbeddedResource Remove="OrdemServicos\Models\**" />
    <None Remove="DTOs\**" />
    <None Remove="Interfaces\**" />
    <None Remove="OrdemServicos\Models\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
