apiVersion: v1
kind: Secret
metadata:
  name: techchallenger-secrets
  namespace: techchallenger-ns
type: Opaque
data:
  ConnectionStrings__DefaultConnection: <BASE64_DA_CONNECTION_STRING_COMPLETA_AQUI>
